---
name: Update repository

on: push

jobs:
  update:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          path: main
      - name: Checkout template repository
        uses: actions/checkout@v2
        with:
          repository: rhasspy/rhasspy-python-template
          path: template
      - name: Update repository from template
        uses: rhasspy/rhasspy-update-repo-action@master
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: main
          branch: update-from-rhasspy-python-template
          commit-message: Update from rhasspy-python-template
          title: Update from rhasspy-python-template
          body: |
            Update files from [rhasspy-python-template](https://github.com/rhasspy/rhasspy-python-template)
